// @index('./*', f => `export * from '${f.path}'`)
export * from './auth.controller'
export * from './auth.module'
export * from './auth.service'
export * from './dto'
export * from './guards'
export * from './meta'
export * from './permission'
export * from './role'
export * from './user'
